CNDB-16484: handle brute force edge case selecting zero vectors (#2202)
### What is the issue
Fixes: https://github.com/riptano/cndb/issues/16484

### What does this PR fix and why was it fixed

When a partition restriction filters down to rows without vectors, we
can get a list of 0 rows, and then we attempt to create a bounded heap
of size 0, which is invalid. The added test catches this error. The
solution is to exit the method early in the event of a zero length
`SegmentRowIdOrdinalPairs` object.

```
java.lang.IllegalArgumentException: initialSize must be > 0 and < 2147483630; got: 0
	at io.github.jbellis.jvector.util.AbstractLongHeap.<init>(AbstractLongHeap.java:52)
	at io.github.jbellis.jvector.util.BoundedLongHeap.<init>(BoundedLongHeap.java:47)
	at io.github.jbellis.jvector.util.BoundedLongHeap.<init>(BoundedLongHeap.java:43)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.orderByBruteForce(V2VectorIndexSearcher.java:328)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.orderByBruteForce(V2VectorIndexSearcher.java:283)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.searchInternal(V2VectorIndexSearcher.java:246)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.orderBy(V2VectorIndexSearcher.java:172)
	at org.apache.cassandra.index.sai.disk.v1.Segment.orderBy(Segment.java:160)
```

 (Rebase of commit 61b48f503c8996b315364e89399542192b8f345b)