Cherry-pick all the fixed about CNDB-13591 into main branch (#1719)
The fix for CNDB-13591 was developed and only committed to the March 25
release branch

commit e3dfead0d0cb616bf8cdd55827933be3850c954e (HEAD ->
cndb-13591-main, origin/cndb-13591-main)
Author: Jacek Lewandowski <lewandowski.jacek@gmail.com>
Date:   Fri Apr 4 16:14:24 2025 +0200

    CNDB-13591: Fix unit tests (missed commit in previous hotfix)

    (cherry picked from commit 7c5130359c398e63db1111c32dc602e7fa3acac7)

commit b1f732efd01f32bcd010293e34650dac280709ca
Author: Enrico Olivelli <enrico.olivelli@datastax.com>
Date:   Fri Apr 4 14:18:30 2025 +0200

CNDB-13591: Error while loading chunkcache:
java.lang.IllegalArgumentException: Negative position (#1677)

    Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
    (cherry picked from commit 09748bdc9122747912fcd8fcc8bd64af3d7f14ce)

commit 4ff4879087d6c8af40c526fdd2b852e54498a039
Author: Branimir Lambov <branimir.lambov@datastax.com>
Date:   Fri Apr 4 14:42:26 2025 +0300

    CNDB-13591: Go back to storing byte buffers in the cache

    (cherry picked from commit 7624a19305d669e79fde01f587fefb64fa2f609e)

---------

Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
Co-authored-by: Jacek Lewandowski <lewandowski.jacek@gmail.com>

 (Rebase of commit 8b21a2d03e4ccd394344e108c2a408823fc47d0a)