CNDB-12915: --add-opens for java.nio.charset (#1581)
### What is the issue
Missing add-opens causes an error while caching PreparedStatement on the
server

```
     java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.nio.charset.Charset.name accessible: module java.base does not "opens java.nio.charset" to unnamed module @6009bea
     	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:388)
     	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:364)
     	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:312)
     	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
     	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
     	at org.github.jamm.MemoryMeter.addFieldChildren(MemoryMeter.java:330)
     	at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:269)
     	at org.apache.cassandra.utils.ObjectSizes.measureDeep(ObjectSizes.java:216)
     	at org.apache.cassandra.cql3.QueryProcessor.measurePStatementCacheEntrySize(QueryProcessor.java:894)
     	at org.apache.cassandra.cql3.QueryProcessor.storePreparedStatement(QueryProcessor.java:757)
```

### What does this PR fix and why was it fixed
Add opens to the JVM arguments