CNDB-13591 ported to May 25 release (#1720)
### What is the issue
The fix for CNDB-13591 was not ported to the May release branch.


### What does this PR fix and why was it fixed
commit 63ab9c44d63223a5a78dd07230cb5e1e9e57ed8b (HEAD ->
cndb-13591-may25, origin/cndb-13591-may25)
Author: Jacek Lewandowski <lewandowski.jacek@gmail.com>
Date:   Fri Apr 4 16:14:24 2025 +0200

    CNDB-13591: Fix unit tests (missed commit in previous hotfix)
    
    (cherry picked from commit 7c5130359c398e63db1111c32dc602e7fa3acac7)

commit 1692a93cc5fbae0a3db025ce7496d04cc4fcac2f
Author: Enrico Olivelli <enrico.olivelli@datastax.com>
Date:   Fri Apr 4 14:18:30 2025 +0200

CNDB-13591: Error while loading chunkcache:
java.lang.IllegalArgumentException: Negative position (#1677)
    
    Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
    (cherry picked from commit 09748bdc9122747912fcd8fcc8bd64af3d7f14ce)

commit c01039b31653ef996c656f8ba27a3032d911164e
Author: Branimir Lambov <branimir.lambov@datastax.com>
Date:   Fri Apr 4 14:42:26 2025 +0300

    CNDB-13591: Go back to storing byte buffers in the cache
    
    (cherry picked from commit 7624a19305d669e79fde01f587fefb64fa2f609e)

---------

Co-authored-by: Branimir Lambov <branimir.lambov@datastax.com>
Co-authored-by: Jacek Lewandowski <lewandowski.jacek@gmail.com>