STAR-561 selectors should contain elements with same type (#169)
* selectors should contain elements with same type

Expressions like "SELECT [(CAST(pk AS BIGINT), CAST(ck AS BIGINT)), (t, WRITETIME(t))] FROM %s"
can't be deserialized. If we try to extract the result by calling
getRows we get:
org.apache.cassandra.serializers.MarshalException: Expected 8 or 0 byte long

This commit makes sure that all collection elements have the
same type.

Co-authored-by: Zhao Yang <zhao.yang@datastax.com>

* test for Maps.getExactMapTypeIfKnow

Maps are a bit different than Lists and Sets. Maps can't be selected
without a type hint, which makes it impossible to exercise query execution
path with `getExactMapTypeIfKnow`. That is why tests for "map SELECTs" are
missing TermSelectionTest.java.
The previous fixed `Maps.getExactMapTypeIfKnow` but it can't be tested in
a similar way as for Lists and Sets. That's why commit adds a separate
unit tests for `Maps.getExactMapTypeIfKnow`.

Co-authored-by: Zhao Yang <zhao.yang@datastax.com>
(cherry picked from commit 78b0117ac1a233de739ed8d17f72d300a81a5fea)
(cherry picked from commit 68984d8f6932c3d5ea56ba5e834213c9cd5dcf11)
(cherry picked from commit 5c359bf1bc4de6c44f8e7c61f64bdc73a9018394)
(cherry picked from commit 84cacddf8bd85ab1c7577c0029071141d643e4d1)
(cherry picked from commit 28be2a403eb72d7f8914ba9c02952c30c4dd0873)
(cherry picked from commit 8dd8b4b5f51ce155dcf379627c2836cfe9293f49)
(cherry picked from commit 7c57b4e288e40790714eba389260727091b288ea)
(cherry picked from commit 0815d7ebe4ac6b16cb52a9a518213df690ce30d0)
(cherry picked from commit a911bdcf6ad83b2442ec038cd0c61b4c02a457c3)

 (Rebase of commit 3893414906db383c0cc0b68da370493afa1cc268)

 (Rebase of commit 0563acde66c0e3c32929bd1d75dddd2b87691066)