Enables access to FileTime private field
When running tests with JDK17 we see NoClassDefFoundError when trying
to instante org.apache.cassandra.Util class due caused by
getSupportedMTimeGranularity trying to access a private field.
This patch modified the build configuration to add a jvm option
allowing that access.