CNDB-18140: CNDB-14041 Fix UnknownKeyspaceException in CompactionMetrics, compaction pressure calculation, and revert table default
Commit 1: CNDB-14041: Fix UnknownKeyspaceException in CompactionMetrics

Fixes:

org.apache.cassandra.exceptions.UnknownKeyspaceException: Could not find a keyspace xxxxx
	at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:368)
	at org.apache.cassandra.db.Keyspace.lambda$open$0(Keyspace.java:168)
	at org.apache.cassandra.utils.concurrent.LoadingMap.lambda$blockingLoadIfAbsent$1(LoadingMap.java:273)
	at org.apache.cassandra.utils.concurrent.LoadingMap.lambda$computeIfAbsent$0(LoadingMap.java:98)
	at org.apache.cassandra.utils.concurrent.LoadingMap.updateOrRemoveEntry(LoadingMap.java:178)
	at org.apache.cassandra.utils.concurrent.LoadingMap.computeIfAbsent(LoadingMap.java:98)
	at org.apache.cassandra.utils.concurrent.LoadingMap.blockingLoadIfAbsent(LoadingMap.java:272)
	at org.apache.cassandra.schema.Schema.maybeAddKeyspaceInstance(Schema.java:246)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:166)
	at org.apache.cassandra.db.Keyspace.open(Keyspace.java:155)
	at org.apache.cassandra.metrics.CompactionMetrics.lambda$new$0(CompactionMetrics.java:115)
	at org.apache.cassandra.db.compaction.CompactionManager.getPendingTasks(CompactionManager.java:2180)

Commit 2: CNDB-14041: Fix compaction pressure calculation in AdaptiveCompressor

Compaction pressure is not allowed to get below 0.

Commit 3: CNDB-14041: Revert enable Adaptive Compression by default for new tables (#2449)

Disable adaptive compression by default, while keeping the fixes and improvements in the
patch that enabled it, https://github.com/datastax/cassandra/pull/2415.

We've decided to revert it in July release, as we do not want this change to happen on
all tenants at the same time.

Forward merging of
 - https://github.com/datastax/cassandra/commit/41a3cea193b1beb64a1a4919f1ffd6d27bbf2d42
 - https://github.com/datastax/cassandra/commit/65107f528d89da610c791363ff37e58c89377018
 - https://github.com/datastax/cassandra/commit/344b02bf6c50e02800c3c006093f370d5b0760c2