CNDB-11630: Minimal port of CASSANDRA-18049 and additional fixes around rolling logs (#1415)
I noticed Python DTests failing with:
failed on teardown with "Failed: Unexpected error found in node logs
(see stdout for full details). Errors: [[node1] 'WARN [RMI TCP
Connection(2)-127.0.0.1] 2024-11-05 04:26:00,950
Slf4jExceptionHandler.java:50 - Cannot get access to vectorizedMismatch.
The following command line args are required: --illegal-access=permit
--add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports
java.base/jdk.internal.util=ALL-UNNAMED. exception:
java.lang.reflect.InaccessibleObjectException: Unable to make public
static int
jdk.internal.util.ArraysSupport.vectorizedMismatch(java.lang.Object,long,java.lang.Object,long,int,int)
accessible: module java.base does not "exports jdk.internal.util" to
unnamed module @73a1e9a9']"

This happens even with JDK11.

https://jenkins-stargazer.aws.dsinternal.org/job/ds-cassandra-build-nightly/1460/testReport/junit/dtest-offheap-bti.fqltool_test/TestFQLTool/tests_stage_2___dtests___dtest_offheap_bti___dtest_offheap_bti_40___test_unclean_enable/
It seems when we updated chronicle in 4fee8631 we missed to add the
recommended by Chronicle exports for JDK11+:
https://chronicle.software/chronicle-support-java-17/
We updated chronicle in
[CASSANDRA-18049](https://issues.apache.org/jira/browse/CASSANDRA-18049)
We may want to consider what was done there more than the versions bump,
in additional to export/open internals

The patch ports partially CASSANDRA-18049
Not pinning particular versions for the transitive dependencies as that
will mean upgrading dependencies which we do not want to do in a patch
release The option we use for deciding how often to roll Audit log
segments is now deprecated and the tools emit a warning about that. Make
a note about the switch of the default roll of Audit segments options to
its new name so it does not emit warnings and update the docs so people
know they can still use the old options but they need to change them
soon. Old ones not recommended for new deployments. Also, we should
change it with main-5.0

If the reviewer approved we leave the old options, we need to add a
patch for cassandra-dtest to skip below warning while checking the test
logs for warnings/errors:
`WARN [RMI TCP Connection(2)-127.0.0.1] 2024-11-08 14:55:32,932
Slf4jExceptionHandler.java:50 - You've configured your queue to use a
deprecated RollCycle (net.openhft.chronicle.queue.RollCycles.HOURLY)
please consider switching to
net.openhft.chronicle.queue.rollcycles.LegacyRollCycles.HOURLY, as the
RollCycle constant you've nominated will be removed in a future
release!`

- [ ] Make sure there is a PR in the CNDB project updating the Converged
Cassandra version
- [ ] Use `NoSpamLogger` for log lines that may appear frequently in the
logs
- [ x] Verify test results on Butler
- [x ] Test coverage for new/modified code is > 80%
- [x ] Proper code formatting
- [x ] Proper title for each commit staring with the project-issue
number, like CNDB-1234
- [x ] Each commit has a meaningful description
- [x ] Each commit is not very long and contains related changes
- [ ] Renames, moves and reformatting are in distinct commits

---------

Co-authored-by: Brandon Williams <brandonwilliams@apache.org>

 (Rebase of commit 8aee0125d70948ef6da49b7383e8b11d750eeaeb)