Attempts to fix RepairJobTest.testNoTreesRetainedAfterDifference
This test is failing in JDK 17 with different exceptions:

```
Unable to make field private java.security.ProtectionDomain[] java.security.AccessControlContext.context accessible: module java.base does not "opens java.security" to unnamed module @598067a5
```

and

```
WARN  [main] 2025-02-17 13:43:07,653 NativeTransportService.java:163 - epoll not available
java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_x86_64
```

and

```
ERROR [RepairJobTask:3] 2025-02-17 13:43:08,418 SystemDistributedKeyspace.java:375 - Error executing query UPDATE system_distributed.repair_history SET status = 'SUCCESS', finished_at = toTimestamp(now()) WHERE keyspace_name = 'RepairJobTest' AND columnfamily_name = 'Standard1' AND id = 1f1d05a0-ed35-11ef-9e08-7193c3f636d0
org.apache.cassandra.db.KeyspaceNotDefinedException: keyspace system_distributed does not exist
	at org.apache.cassandra.schema.Schema.validateTable(Schema.java:479)

```