SAI Update: ignore TTL when getting old row's vector value (#1240)
* Add failing test

java.lang.IllegalArgumentException: value already present: 0

	at com.google.common.collect.HashBiMap.put(HashBiMap.java:279)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:260)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorPostingsWriter.buildOrdinalMap(V2VectorPostingsWriter.java:195)
	at org.apache.cassandra.index.sai.disk.v2.V2VectorPostingsWriter.remapPostings(V2VectorPostingsWriter.java:209)
	at org.apache.cassandra.index.sai.disk.vector.CassandraOnHeapGraph.flush(CassandraOnHeapGraph.java:392)
	at org.apache.cassandra.index.sai.disk.vector.VectorMemtableIndex.writeData(VectorMemtableIndex.java:407)
	at org.apache.cassandra.index.sai.disk.v1.MemtableIndexWriter.flushVectorIndex(MemtableIndexWriter.java:212)
	at org.apache.cassandra.index.sai.disk.v1.MemtableIndexWriter.complete(MemtableIndexWriter.java:124)
	at org.apache.cassandra.index.sai.disk.StorageAttachedIndexWriter.complete(StorageAttachedIndexWriter.java:214)
	at org.apache.cassandra.io.sstable.format.SSTableWriter.lambda$prepareToCommit$1(SSTableWriter.java:344)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at org.apache.cassandra.io.sstable.format.SSTableWriter.prepareToCommit(SSTableWriter.java:344)
	at org.apache.cassandra.db.compaction.unified.ShardedMultiWriter.prepareToCommit(ShardedMultiWriter.java:257)
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.flushMemtable(ColumnFamilyStore.java:1406)
	at org.apache.cassandra.db.ColumnFamilyStore$Flush.run(ColumnFamilyStore.java:1315)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

* SAI Update: ignore TTL when getting old row's vector value

* Improve comment

 (Rebase of commit 86fc71c7b0a0b692b573b8ada9fc06035406437e)

 (Rebase of commit ed9f5a309670222b6565d8c1aa7222064a942f35)