Fix hybrid vector query bug when sstable has rows with null vectors (#1269)
Fixes https://github.com/riptano/cndb/issues/10810

We hit:

```
java.lang.AssertionError: sstableRowId 315407 > maxSSTableRowId 315406
     	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.flatmapPrimaryKeysToBitsAndRows(V2VectorIndexSearcher.java:615)
     	at org.apache.cassandra.index.sai.disk.v2.V2VectorIndexSearcher.orderResultsBy(V2VectorIndexSearcher.java:509)
     	at org.apache.cassandra.index.sai.disk.v1.Segment.orderResultsBy(Segment.java:183)
     	at org.apache.cassandra.index.sai.disk.v1.V1SearchableIndex.orderResultsBy(V1SearchableIndex.java:213)
     	at org.apache.cassandra.index.sai.SSTableIndex.orderResultsBy(SSTableIndex.java:292)
     	at org.apache.cassandra.index.sai.plan.QueryController.lambda$orderSstables$10(QueryController.java:623)
     	... 23 common frames omitted
```

Notably, this bug happened after compaction, not just after flush. I added a new utility method to make it easier to test compaction code path.

 (Rebase of commit 302c057f952d274b7af1073ad4d8d409c7a5a2a5)

 (Rebase of commit 9fc1c70b5f1087ec7c3ad810618fd677a5126321)