STAR-540: Don't query index in unknown state
Allow index to be queried only if its status is known
to be BUILD_SUCCEEDED. For all the other states,
including the UNKNOWN state, it is inherently dangerous
to query such index. A query to an index that's
in the middle of building process may return incomplete
results.

Fixes flakyness of QueryWriteLifecycleTest manifested as:

    junit.framework.AssertionFailedError: expected:<[MS, AL, TN, UT, KY, LA]> but was:<[MS, AL, TN, KY, LA]>
	    at org.apache.cassandra.index.sai.cql.IndexQuerySupport$BaseQuerySet.validate(IndexQuerySupport.java:568)
	    at org.apache.cassandra.index.sai.cql.IndexQuerySupport$BaseQuerySet.rangeQuery(IndexQuerySupport.java:551)
	    at org.apache.cassandra.index.sai.cql.IndexQuerySupport$BaseQuerySet.execute(IndexQuerySupport.java:354)
	    at org.apache.cassandra.index.sai.cql.IndexQuerySupport.executeQueries(IndexQuerySupport.java:215)
	    at org.apache.cassandra.index.sai.cql.IndexQuerySupport.writeLifecycle(IndexQuerySupport.java:97)
	    at org.apache.cassandra.distributed.test.sai.QueryWriteLifecycleTest.testWriteLifecycle(QueryWriteLifecycleTest.java:30)

Additionally, this commit fixes the code for waiting for index readiness in SAIUtil.
The original code ignored the fact that if the schema with the new index
hasn't been propagated to the other node yet, that node does not know anything
about the index and doesn't return its status. Unfortunately a
lack of status was considered as "index queryable" and the waiting
didn't happen.

SAIUtil.waitForIndexQueryable has been modified to rely on index status from
gossip. This way it can see the exact same state that a coordinator
uses to determine index availability. The downside is that now some tests
need to run with gossip enabled.