CNDB-6235 messaging metrics impl is configurable (#594) Fix compilation of MessagingService (#595)
Fixes:
  [javac] cassandra/src/java/org/apache/cassandra/net/MessagingService.java:219: error: cannot find symbol
    [javac]     static Map<Integer, Integer> versionOrdinalMap = Arrays.stream(Version.values()).collect(Collectors.toMap(v -> v.value, v -> v.ordinal()));
(cherry picked from commit 4904d4f2fd199f18e63c39590481fe4123c9c3d9)
(cherry picked from commit 2303a0bd598ae86d333ea7d4b3c7e09da65b4d16) (+1 squashed commit)
Squashed commits:
[17aee9223e] CNDB-6235 messaging metrics impl is configurable (#594)

* messaging metrics impl is configurable

*  internal latency gets `from` address

Overriding cndb method will use it to record metrics per
"from-dc", similarly to internodeLatencyRecorder

(cherry picked from commit 142bb94d0336a700041bc7b11d98ab21473045bc)
(cherry picked from commit 35fe294ce15c0c3c2e70cd090208f70b6ddb1c78)
(cherry picked from commit a76587caa18cbd81739d0c7d52b1aa5ca16e4ee5)

 (Rebase of commit ef47bc65e3f6663eb7bad2ed2b98ff0e35d6d083)